### ISSUE TITLE
differenze

### ISSUE THREAD

**Issue by SiNaPsEr0x** [Cioscos/DeepFaceLab-Colab#1]
differenze dalla principale? è fatto meglio ? piu semplice?

**Comment by Cioscos** [comment]
Non è più semplice, ha molte più impostazioni e alcune sono fatte per gestire anche altri fork di DeepFaceLab come quello di MVE.

**Comment by Cioscos** [comment]
Questo è il link: https://github.com/MachineEditor/DeepFaceLab/wiki
