### ISSUE TITLE
safari alle volte si disconnette

### ISSUE THREAD

**Issue by SiNaPsEr0x** [Cioscos/DeepFaceLab-Colab#2]
siamo sicuri che funziona? perchè sia con safari che con firefox ahime si disconnette e si perde il lavoro... puo essere che è cambiato il comando del puntatore?

```
import IPython
from google.colab import output

display(IPython.display.Javascript('''
 function ClickConnect(){
   btn = document.querySelector("colab-connect-button")
   if (btn != null){
     console.log("Click colab-connect-button"); 
     btn.click() 
     }
   
   btn = document.getElementById('ok')
   if (btn != null){
     console.log("Click reconnect"); 
     btn.click() 
     }
  }
  
setInterval(ClickConnect,60000)
'''))

print("Done.")
```

**Comment by Cioscos** [comment]
Si, il problema non è del notebook bensì di Colab.

**Comment by SiNaPsEr0x** [comment]
Provo con chrome su Mac….. o è un metodo diciamo per “bloccar L attività”?

**Comment by Cioscos** [comment]
Sconsiglio fortemente l'utilizzo di un borwser diverso da Chrome o comunque un dispositivo diverso dal un computer, in quanto la scheda del browser (almeno che non si possiede un abbonamento Colab Pro+) deve sempre rimanere aperte.

Ti informo che nel caso tu usassi un abbonamento Free di Colab non ti sarà possibile eseguire deepfake.

Mentre se paghi colab, esso dal 29 settembre ha cambiato sistema e ora funziona a token.

**Comment by SiNaPsEr0x** [comment]
Ho preso il pay for use... sto provando adesso con Chrome su Mac... vediamo un po' 



Grazie comunque del feedback ☺️

**Comment by SiNaPsEr0x** [comment]
Niente si blocca uguale a random...
