### ISSUE TITLE
DST/SRC extraction and training failing

### ISSUE THREAD

**Issue by fulanito3030** [Cioscos/DeepFaceLab-Colab#3]
Hello,

I tried to use extract DST and SRC faces it it does not work. I also tried to train and it also does not work. I have attache the error messages for you to review.

Thanks!!

<img width="1227" alt="Screenshot 2024-02-13 at 5 37 27 PM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/b45fb397-06f5-4ec0-9889-b64f50d0884f">
<img width="1181" alt="Screenshot 2024-02-13 at 5 49 04 PM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/0150a090-031a-4027-a4a0-df5582a7104b">

**Comment by fulanito3030** [comment]
This is the error text. It seems it's an issue with numpy. 



Error while processing data: Traceback (most recent call last):
  File "/content/DeepFaceLab/core/joblib/SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "/content/DeepFaceLab/mainscripts/Extractor.py", line 201, in process_data
    data = ExtractSubprocessor.Cli.rects_stage (data=data,
  File "/content/DeepFaceLab/mainscripts/Extractor.py", line 246, in rects_stage
    rects = data.rects = rects_extractor.extract (rotated_image, is_bgr=True)
  File "/content/DeepFaceLab/facelib/S3FDExtractor.py", line 196, in extract
    for ltrb in self.refine (olist):
  File "/content/DeepFaceLab/facelib/S3FDExtractor.py", line 245, in refine
    bboxlist = [ x[:-1].astype(np.int) for x in bboxlist if x[-1] >= 0.5]
  File "/content/DeepFaceLab/facelib/S3FDExtractor.py", line 245, in <listcomp>
    bboxlist = [ x[:-1].astype(np.int) for x in bboxlist if x[-1] >= 0.5]
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by fulanito3030** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
Successfully installed scipy-1.10.0
Collecting colorama==0.4.6
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: colorama
Successfully installed colorama-0.4.6
Collecting tf2onnx==1.14.0
  Downloading tf2onnx-1.14.0-py3-none-any.whl (451 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 451.2/451.2 kB 9.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.1 in /usr/local/lib/python3.10/dist-packages (from tf2onnx==1.14.0) (1.25.2)
Collecting onnx>=1.4.1 (from tf2onnx==1.14.0)
  Downloading onnx-1.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 62.5 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from tf2onnx==1.14.0) (2.31.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from tf2onnx==1.14.0) (1.16.0)
Collecting flatbuffers<3.0,>=1.12 (from tf2onnx==1.14.0)
  Downloading flatbuffers-2.0.7-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from onnx>=1.4.1->tf2onnx==1.14.0) (3.20.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->tf2onnx==1.14.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->tf2onnx==1.14.0) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->tf2onnx==1.14.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->tf2onnx==1.14.0) (2024.2.2)
Installing collected packages: flatbuffers, onnx, tf2onnx
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 23.5.26
    Uninstalling flatbuffers-23.5.26:
      Successfully uninstalled flatbuffers-23.5.26
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.15.0 requires flatbuffers>=23.5.26, but you have flatbuffers 2.0.7 which is incompatible.
Successfully installed flatbuffers-2.0.7 onnx-1.15.0 tf2onnx-1.14.0

**Comment by Cioscos** [comment]
Hi! The error is not depending on my colab in itself but on a different way that numpy works. Probably Colab updated the numpy version which installs.
I suggest you to add immediately after:

```python
if Mode != 'remove':
```
the command: !pip install numpy==1.19.5

If this fix works, I'll commit this change

**Comment by fulanito3030** [comment]
Great! I will test and let you know. Thank you sir!

**Comment by fulanito3030** [comment]
Hi,

I tried the fix and it still doesn't work. I added the command you suggested and during install I got more. Attached are some screen shots.  I also did some research and it looks like Colab now runs python 3.10. Maybe the new python versions requires updated versions of the dependencies. 

- https://colab.google/articles/py3.10

Please let me know if you need help or more testing. 

[
![numpy](https://github.com/Cioscos/DFL-Colab/assets/99452881/0c50cf2e-fefc-47ac-887c-92b1622d5311)
](url)

<img width="974" alt="Screenshot 2024-02-14 at 6 24 15 PM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/bd0e1bd2-c662-4d6d-9aaf-e5130185a718">
<img width="1138" alt="Screenshot 2024-02-14 at 6 24 29 PM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/c6ab0f2b-471e-41d7-afea-3f81957d2e16">
<img width="1049" alt="Screenshot 2024-02-14 at 6 24 23 PM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/cccca592-e17e-4be8-bbf8-ac3ee1a12fc9">

**Comment by Cioscos** [comment]
Try to add

!pip install wheel

Before install numpy

**Comment by fulanito3030** [comment]
Hi,

I tried your suggested and I still got errors. But I was on the mr.deepfakes forum and found the following code as a workaround:

<img width="412" alt="Screenshot 2024-02-15 at 7 00 26 AM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/bae38942-276c-42a0-abc7-15d6b0fde8c9">

I was able to extract faces but NOT train. Hmmm what do you think?

**Comment by fulanito3030** [comment]
Hello,

I have another update. It now works. I used the following code in the following location:

I did not change the code section. I added updated pip install to the beginning of the code within the install cell. I don't know if this a good solution but it works...for now. What do you think?

![update1](https://github.com/Cioscos/DFL-Colab/assets/99452881/1ac3a1bc-26a1-4356-9d5d-3ed0f5b302f2)

<img width="639" alt="Screenshot 2024-02-15 at 8 48 36 AM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/5a230b52-efca-4230-b201-4e8d6f9bff92">

**Comment by Cioscos** [comment]
The position of that line of code is not important. In general, it should stay in the "if" I said to you.

If you put it there does it work? If yes I edit my notebook

**Comment by fulanito3030** [comment]
as of right now, it is working. Let me do some more testing and training and i will get back to you. Will tomorrow be ok?

**Comment by Cioscos** [comment]
Of corse, no hurry

**Comment by fulanito3030** [comment]
Thank you, bro!

**Comment by fulanito3030** [comment]
Hi,

I can confirm the fix of adding !pip install numpy==1.23.5 the section you have identified makes the notebook function. 
<img width="612" alt="Screenshot 2024-02-15 at 1 35 04 PM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/e6183397-be4f-41ed-82c2-a2e92cd41faa">

Below are the images of what happens after !pip install numpy==1.23.5 is added to the code. There are 3 things in red text but the notebook still works. I don't know if this normal or good or bad? 

<img width="1226" alt="Screenshot 2024-02-16 at 2 35 53 PM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/41dc9988-c1dc-4a37-9cd2-a13f0ced34c8">
<img width="981" alt="Screenshot 2024-02-16 at 2 36 00 PM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/28ecff59-54c2-47df-b823-3b098ee104f9">
<img width="1165" alt="Screenshot 2024-02-16 at 2 36 04 PM" src="https://github.com/Cioscos/DFL-Colab/assets/99452881/49412f0b-78df-43ab-ad30-dafb3083bb28">

I can verify the following works:

1. frame extraction
2. Face extraction (dst/src)
3. Apply xseg
4. Xseg training
5. Model training (SAEHD/AMP)
6. Frame merge
7. Result

Let me know if you have any more questions!

**Comment by Cioscos** [comment]
Fixed
